# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 637bee0a0c5e150a169d47b7b628928c95f4f9548cea8a389e059ae4309f9b8f22f26bafc8fe1a10474a0768e8c36285fcead64c5907eafb1cf9c37ddb9d8dd0

test:
  secret_key_base: 8a2edd45482fca1a76f304c46fe90c3c33ceb84caf0d7a2f5f234d79f0020518e66f79aef55ed9496f54a18abb9ba88ae195531f5f471adad41548594a154d54

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
